server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public;

    # Xử lý route: nếu file không tồn tại, chuyển sang index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Xử lý các file PHP: chuyển tiếp đến container app qua php-fpm
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Cấu hình cho các file tĩnh (CSS, JS, hình ảnh)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        try_files $uri =404;
    }
}
